# Generated by Django 4.2.29 on 2026-03-04 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availabilityslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default='temp_password', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(default='temp_user', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='api_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.availabilityslot'),
        ),
    ]
